CREATE DATABASE blo;

USE blo;

CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	role VARCHAR(30) NOT NULL DEFAULT 'visiteur',
	password VARCHAR(40),
	pseudo VARCHAR(80) NOT NULL,
	email VARCHAR(255) NOT NULL DEFAULT 'visiteur@gmail.com'
	);

CREATE TABLE comment (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	blog_post_id INT NOT NULL,
	message TEXT NOT NULL,
	date_display date  
	);

CREATE TABLE blog_post (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	author VARCHAR(30) NOT NULL,
	title VARCHAR(80) NOT NULL,
	chapo VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	image VARCHAR(255) NOT NULL,
	date_display date  
	);



ALTER TABLE comment
ADD CONSTRAINT fk_user_id
	FOREIGN KEY (user_id)
	REFERENCES user(id);

ALTER TABLE comment
ADD CONSTRAINT fk_blog_id
	FOREIGN KEY (blog_post_id)
	REFERENCES blog_post(id);

ALTER TABLE blog_post
ADD CONSTRAINT fk_user
	FOREIGN KEY (user_id)
	REFERENCES user(id);




INSERT INTO user (id, role, password, pseudo, email)
VALUES				(1, "administrateur", SHA1("dav"), "dav", "davnice@gmail.com"),
					(2, "visiteur", "NULL", "eric", "davnice@gmail.com"),
					(3, "visiteur", "NULL", "jeremi", "davnce@gmail.com"),
					(4, "visiteur", "NULL", "jerome", "davce@gmail.com"),
					(5, "visiteur", "NULL", "jeje", "davnc@gmail.com"),
					(6, "visiteur", "NULL", "loulou","davni@gmail.com");


INSERT INTO comment (id, user_id, blog_post_id, message, date_display)
VALUES				(1, 2, 1, "Salut la forme ?", "NULL"),
					(2, 3, 2, "Parfait tout foncionne", "NULL"),
					(3, 4, 3, "Juste un test", "NULL"),
					(4, 5, 4, "Très bon l'article", "NULL"),
					(5, 6, 5, "A lire !", "NULL"),
					(6, 4, 6, "Fabuleux !", "NULL");

INSERT INTO blog_post (id, user_id, author, title, chapo, content, image, date_display)
VALUES				(1, 1, "Quentin Périnel", "Développeur web", "Un métier tendance en voie de disparition", "FOCUS - L'avenir du développeur web est-il mis en péril par l'intelligence artificielle ? Un métier pourrait donc être à la fois «tendance», convoité par les entreprises... mais dont les jours sont déjà comptés. Le Figaro fait le point sur ce paradoxe.

Le métier de développeur web a le vent en poupe. Depuis les années de la bulle internet, entre 1990 et 2000, et depuis 2005, les entreprises qui opèrent leur transformation digitale se les arrachent. Si bien que sur le marché du travail, le développeur est un profil rare. La pénurie dure depuis plusieurs années. En matière de formation, l'offre s'est donc très largement élargie pour satisfaire la demande. «Apprendre à coder est devenu une obsession, explique au Figaro Noël Paganelli, patron de «La Capsule Academy», une école de code lyonnaise. Jeunes diplômés d'écoles de commerce, actifs de 30-35 ans en reconversion... L'attrait pour le code et le métier de développeur ne cesse de s'accroître.»

Développeur web, le métier de demain? Si l'on en croit la demande des entreprises et les salaires - parfois mirobolants - que l'on propose pour ce poste, il est fort aisé de le croire... Dans une étude dévoilée par LinkedIn en 2016, on constate que les profils de ceux qui savent coder, développer, programmer et vendre occupent les premières places du «top 20» des métiers les plus recherchés sur le réseau social professionnel. Et pourtant, «développeur» fait partie de ces métiers qui ont le vent en poupe mais dont l'existence est d'ores et déjà mise en péril par l'intelligence artificielle.

Paradoxal? «La machine de l'IA est en marche, et l'on sait que cette pénurie de développeurs est provisoire», précise Noël Paganelli, qui cherche à anticiper les dégâts que vont causer l'IA à son offre de formation... en même temps qu'il la développe! «On sent le vent tourner. Et on réfléchit pour s'armer le mieux possible afin d'humaniser notre travail et amplifier la partie créative», précise-t-il.

Quel degré de créativité pourra atteindre l'IA?
«Humaniser son travail.» Et se demander quelle tâche peut être copiée par l'IA et quelle tâche ne peut - a priori - pas l'être. «La vérité est grise, explique au Figaro Philippe Silberzahn, professeur à l'EM Lyon et chercheur associé à l'École Polytechnique. Beaucoup d'aspects du codage vont être automatisés, et donc penser que «tout le monde doit apprendre à coder» me semble idiot, même si une culture du codage est intéressante et utile, tout comme une culture classique. Mais à mon avis, il restera toujours des domaines où la créativité du codeur sera nécessaire. C'est d'ailleurs vrai, je crois, dans tous les domaines.» Tout ce qui est lié à la créativité fait effectivement partie des plates bandes sur lesquelles l'IA interviendra plus difficilement.", "public/images/1.jpg", "NULL"),
					(2, 1, "Par  Marc Rameaux", "Intelligence artificielle, quand Elon Musk s'alarme de ses propres créations ", "L'Intelligence artificielle constitue un risque majeur pour la civilisation » a récemment déclaré Elon Musk, PDG notamment de Neuralink, start-up dont l'objectif est d'ajouter au cerveau humain une part d'intelligence artificielle. Marc Rameaux analyse la dérégulation transhumaniste qui nous guette.", "Marc Rameaux est Directeur de projet dans une grande entreprise industrielle. Il est l'auteur de Portrait de l'homme moderne. Vous pouvez également retrouver ses chroniques sur son blog: Le troisième homme

«L'Intelligence artificielle constitue un risque majeur pour la civilisation». Ainsi s'exprimait Elon Musk samedi dernier, lors du séminaire d'été de l'US National Governors Association à Rhode Island. Le patron de Tesla en appelle à la mise en place urgente d'une régulation sur les technologies d'IA, craignant qu'elles ne dépassent l'homme dans tous les domaines et déstabilisent gravement la société.

L'avertissement de Musk peut faire sourire à deux titres. En premier lieu, ne fait-il pas partie des NATU, acronyme complémentaire des GAFA, qui agrège Netflix, Airbnb, Tesla et Uber? Or, les NATU sont une surenchère dans la voracité des champions technologiques, faisant passer les GAFA pour des enfants de chœur.

Les GAFA ont été capables de piétiner la propriété intellectuelle par des projets de numérisation massive, de violer la confidentialité de nos données personnelles et de les commercialiser auprès de tiers inconnus, enfin de s'affranchir de toute loi fiscale ou régulatrice. Les NATU franchissent un cran supplémentaire dans la dérégulation dévastatrice, par une précarisation croissante de leurs salariés, des pratiques commerciales relevant du dumping ou de la spéculation immobilière, des clauses d'utilisation de leurs produits ne protégeant plus leurs clients ou pouvant être modifiées sans leur avis.

Les déclarations fracassantes de Musk (il n'en est pas à sa première concernant l'IA) semblent plus relever de la publicité en faveur de ses marques que de la préoccupation humaniste.

La puissance et l'extra-territorialité des transactions du Web rendent leur contrôle quasi impossible. L'on peut donc s'amuser de voir l'un des piliers des NATU en appeler à davantage de régulation.

L'autre point d'ironie est que les déclarations fracassantes de Musk - il n'en est pas à sa première concernant l'IA - semblent plus relever de la publicité en faveur de ses marques que de la préoccupation humaniste. La prise de contrôle de nos sociétés par les machines reste une préoccupation mineure comparée aux dangers de la surpopulation, de l'inégalité des revenus ou de la montée des fondamentalismes.

Faut-il donc répondre à cet appel par un haussement d'épaules? Non, car au-delà de l'aspect effrayant et caricatural des NATU, comprendre la Valley et les leçons que nous devrions en tirer, c'est aussi comprendre un entrepreneur tel que Musk. S'il faut s'inquiéter d'une course à l'innovation qui prépare le terrain de la course à la dérégulation, l'argument du grand méchant loup à l'encontre des NATU et GAFA relève de l'infantilisme.

La Valley regorge de ces personnalités paradoxales, que certains dénoncent comme de jeunes vampires prêts à tout pour être reconnus et que d'autres encensent comme des visionnaires animés de réels buts philanthropiques. Ce que l'on ne voit pas est que ces deux facettes sont également vraies, et qu'une personnalité comme Musk en est l'une des meilleures incarnations.

Si les visions d'Elon Musk ont souvent paru souligner les extravagances de la Valley, elles se sont avérées profondes avec le temps et le patron de Tesla mérite en cela le respect. Ce qu'il souligne concernant l'IA ne fait pas exception: il détecte un danger d'autant plus critique qu'il est peu apparent. La menace de l'IA ne se trouve pas là où nous le pensons.

La peur d'une machine qui gagne son autonomie est plus ancienne que l'IA

Les dangers de l'IA ont été perçus bien à l'avance par l'imagination humaine, y compris avant même que l'IA n'existe concrètement. De HAL, l'ordinateur fou de 2001 l'odyssée de l'espace, à Ultron en passant par Terminator, l'idée d'une intelligence capable de comprendre, décider et agir au moins aussi bien qu'un être humain, pour s'émanciper de celui-ci jusqu'à décider de l'éliminer, a alimenté les meilleurs auteurs d'œuvres fantastiques.

C'est un auteur français qui a perçu le plus en avance ces questions. En plein XIXème siècle, Villiers de L'Isle-Adam écrivait «L'Ève future», imaginant une Andréide créée par Edison, pour se substituer à la femme aimée d'un jeune lord Anglais. L'auteur français anticipe ces sordides poupées d'amour que la technologie met à présent sur le marché dans des versions de plus en plus perfectionnées et pousse le génie jusqu'à mettre en scène un véritable test de Turing que son andréide réussit, des décennies avant que le logicien anglais n'en définisse le protocole.

Le thème du cyborg tueur ou trompeur apparut presque aussi rapidement que la fabrication des premiers automates. Parfois le rapport est inversé, l'être artificiel nous renvoyant à notre inhumanité et notre indifférence postmoderne, tels les répliquants de Blade Runner ou le petit garçon robot aimant désespérément sa maman de chair et de sang dans l'AI de Spielberg: dans ce cas, les êtres fabriqués se révèlent plus empathiques qu'une humanité dévastée par la poursuite de ses buts égoïstes.

Une intelligence artificielle est finalisée dans un certain but, dont elle optimisera l'atteinte avec une efficacité supérieure à la nôtre. Si la machine est dotée d'autonomie, elle peut arriver à la conclusion que le peu de fiabilité des humains est un obstacle au but pour lequel elle est programmée. L'humain devra alors être éliminé comme une scorie gênante, au mieux toléré en exigeant de lui une adaptabilité croissante aux besoins du processus. Le concepteur humain prévoit bien sûr un bouton de mise à l'arrêt. Mais le problème advient lorsque nos machines pensantes acquièrent une autonomie telle que l'idée leur vient de supprimer le bouton…

La notion de robot tueur ne relève pas de la prospective lointaine, elle est déjà une réalité.

La notion de robot tueur ne relève pas de la prospective lointaine, elle est déjà une réalité. Les interventions militaires de drones, ont déjà fait des centaines de victimes civiles. En avril 2015, deux otages d'Al-Qaïda membres d'une ONG furent tués par un drone à la frontière pakistano-afghane, obligeant Barack Obama à une reconnaissance publique de l'erreur et à une indemnisation des familles des victimes.

Dans le développement des voitures autonomes, des questions éthiques se posent si dans une situation très critique, la voiture robot n'a plus le choix qu'entre de mauvaises solutions mettant la vie humaine en danger. Il devra alors prendre la décision de savoir qui sera sacrifié, de la vieille dame qui traverse, de l'enfant se trouvant de l'autre côté du passage piéton, de l'homme qui conduit la voiture adjacente, ou de son propre passager humain.

La nécessité d'une régulation du comportement des robots apparut presque aussi vite que son invention: les trois lois d'Asimov sont devenues une réalité plus que tangible avec les 23 principes d'Asilomar édictés en janvier 2017, soutenus par plus de 2000 signataires parmi les meilleurs scientifiques et industriels du domaine, dont Elon Musk et Stephen Hawking. Ces règles sont destinées à doter la recherche en IA d'un surmoi, un rappel des buts humains pour lesquels elle a été conçue initialement.

L'étrange résonance entre IA en réseau et dérégulation économique

Pourquoi Elon Musk perpétue-t-il donc cette inquiétude, quant à une technologie qui semble être en bonne voie de régulation? Parce qu'il a très bien perçu qu'au-delà des intentions, nous pourrions perdre le contrôle des machines pensantes de la même façon et pour les mêmes raisons que nous perdons le contrôle des régulations économiques. Nous allons le voir, l'IA est en quelque sorte une extension surpuissante prolongeant le libéralisme économique, pouvant en amplifier les effets non contrôlés dans des proportions inconcevables.

Pour comprendre ce nouveau danger, nous devons introduire une brève distinction technique. L'IA emploie des méthodes assez variées, pouvant se ramener cependant à deux grandes catégories: les approches «cognitivistes» et «connexionnistes».

Les premières correspondent à la tentative naturelle de fabriquer une intelligence: elles modélisent le raisonnement, posent un univers de règles et d'inférences, déduisent et concluent avant d'agir. Elles «comprennent» les problèmes qu'elles abordent, dans la mesure où elles apprennent à les interpréter. Ces approches sont sans danger, car elles restent entièrement traçables: nous pouvons à tout moment détecter et comprendre pourquoi la machine a pris telle ou telle décision. Ces approches ont connu un certain succès au début de l'IA, mais se sont révélées insuffisantes face à certains problèmes complexes, notamment ceux visant à reconnaître des formes, à synthétiser des informations continues, à mimer au plus près le comportement humain.

L'approche connexionniste emploie une tout autre notion, celle d'intelligence collective. Elle met en œuvre un très grand nombre de petites unités simples, souvent inspirées du vivant telles que les neurones, pourvues d'une faible intelligence individuelle, mais de capacités phénoménales lorsqu'elles agissent en réseau. L'unité élémentaire est une cellule répondant à des stimuli d'entrée par quelques réponses simples, qu'elle propage aux cellules environnantes. Le réseau connexionniste n'a aucune «compréhension» de la situation à laquelle il est confronté: il se contente de répondre à des stimuli par d'autres stimuli.

L'approche connexionniste est l'intelligence de la fourmilière : chaque unité est rudimentaire, mais collectivement, elle atteint une capacité très supérieure.

Des lois très simples régissent les connexions entre les cellules: lorsque deux d'entre elles sont excitées conjointement, leur liaison se renforce, dans le cas contraire, leur liaison s'affaiblit. Ce réseau de liaisons sait très mal répondre à ce qu'on lui demande d'apprendre au tout début. Mais rapidement, en lui montrant un très grand nombre d'exemples de réponses qu'il doit associer aux données qu'il reçoit, il se renforce constamment en pertinence et en précision, jusqu'à obtenir une efficacité sans égale.

L'approche connexionniste est l'intelligence de la fourmilière: chaque unité est rudimentaire, mais collectivement, elle atteint une capacité très supérieure à la somme des capacités individuelles de ses membres. Les sciences cognitives expliquent encore mal comment un réseau de cellules simples obéissant à quelques lois de renforcement de leurs liaisons peut arriver à s'adapter et à résoudre les problèmes les plus complexes. Elles parlent de «qualités émergentes», «d'auto organisation», mais plus pour en constater l'efficacité que la prouver.

Caractéristique gênante, les approches connexionnistes sont quasiment intraçables, contrairement aux approches cognitivistes. Il n'est plus possible d'expliquer simplement pourquoi le réseau a pris telle ou telle décision, le résultat étant noyé dans un jeu d'innombrables pondérations croisées dont on ne peut retrouver le fil. Une approche purement connexionniste est pour cette raison non admissible dans une voiture autonome. Des tentatives ont été faites de reconstituer le «raisonnement» du réseau, mais elles sont encore peu convaincantes.

Le danger ne viendra pas d'un cyborg tueur, mais de millions de petites cellules intelligentes, agissant en réseau, s'auto-renforçant et évoluant en permanence jusqu'à la mutation.

Cet élément technique acquis, nous pouvons comprendre que le danger ne viendra pas d'un cyborg tueur, mais de millions de petites cellules intelligentes, agissant en réseau, s'auto-renforçant et évoluant en permanence jusqu'à la mutation.

La puissance de l'intelligence répartie est d'autant plus redoutable qu'elle est disséminée. Et la dissémination suprême consiste évidemment à être répartie partout sur le Web. Une interview de Musk et de Sam Altman, responsable de l'un des principaux incubateurs de la Valley, est plus qu'explicite: la question n'est pas celle du robot, qui n'est qu'un ensemble de capteurs et d'actionneurs, mais des algorithmes se trouvant sur le Web, selon les propres termes de Musk.

L'IA redoutable est immatérielle: pas de manchette d'acier ou de rayon fatal comme le veulent les séries B de science-fiction, mais des millions de petits logiciels répartis, peu intelligents en eux-mêmes mais agissant en réseau de façon coordonnée, parvenant à une maîtrise collective stupéfiante mais non traçable et sans qu'une entité en particulier ne soit responsable.

Quels pourraient être ces dangers d'une telle IA répartie? Nous savons déjà que des algorithmes complexes flairent nos moindres goûts et centres d'intérêt pour nous présenter des propositions alléchantes à chaque détour d'un site de commerce en ligne. L'anticipation de nos désirs par recoupement d'informations atteint parfois une précision si confondante qu'elle est inquiétante.

Étendons cette compréhension fine à d'autres domaines. La tarification de tous les services auxquels nous souscrivons peut-être rendue totalement variable, ajustable en temps réel. Irréaliste? C'est pourtant le cas de nos billets de train, dont le prix varie très fortement en fonction du moment. La tarification variable possède une justification très rationnelle, celle d'optimiser les pics de charge d'utilisation du service, en incitant à se présenter aux heures creuses. Ceci conduisit Uber à demander des tarifs exorbitants lors des attentats de Londres, simplement parce que l'algorithme calculait que les taxis devenaient une denrée rare et que l'on pouvait profiter de ce nouvel ajustement de l'offre et de la demande… Les algorithmes n'avaient aucune éthique vis-à-vis de la détresse dans laquelle se trouvaient les passants, l'optimisation du mieux-disant étant leur seule logique.

Si les services deviennent ainsi ajustables, changeant leurs tarifs sans prévenir et sans aucune notion d'engagement, pourquoi ne pas étendre de tels principes au droit du travail? Des algorithmes répartis mondialement compareraient en permanence les salaires, taux de disponibilité et productivité de chacun, et ajusteraient un contrat de travail instantané en permanence. La flexibilité parfaite, justifiée par le fait qu'ainsi chacun serait payé exactement à sa juste valeur, instantanément remplaçable si l'opportunité le permet. Nul souci dans cette belle optimisation, de la précarité qui interdirait tout projet personnel ni du long terme nécessaire au développement d'un être humain.

L'on ne pourrait confier ainsi notre avenir à un tel système de calcul? Nous venons pourtant de vivre une affectation des bacheliers dans les universités selon un algorithme de tirage aléatoire, soumettant les destins personnels de milliers d'étudiants au résultat arbitraire d'un algorithme. Celui-ci ne comportait pas d'IA, mais précisément imaginons son usage dans des cas touchant à nos études ou notre emploi: la décision est indétectable, non reconstituable, et sans responsable identifié car disséminée dans les interactions de milliers de modules coopératifs. Restera l'argument massue de considérer qu'il ne peut s'agir que de la décision la plus optimisée, donc ne souffrant aucune discussion.

Le droit du travail étant attaqué, pourquoi ne pas élargir le champ au droit tout court? Impossible? Le cabinet d'avocats BakerHostetler emploie depuis 2016 Ross, une IA fondée sur une technologie d'IBM effectuant en quelques secondes l'équivalent de milliers d'heures de travail de recherche dans les textes par des avocats humains. Les cols blancs ne sont pas plus épargnés par les menaces que l'IA fait planer sur leur emploi, avec une ubérisation de la profession d'avocat désormais en marche.

La logique du mieux disant qui est la seule loi des réseaux connexionnistes pourrait aboutir à des dérapages très dangereux dans le domaine du droit. Nos sociétés postmodernes ont de plus en plus tendance à relâcher l'universalité de la loi pour céder à son adaptation régionale voire à son complet morcellement selon les villes et quartiers. L'on voit ainsi régulièrement des élus nous expliquer que l'interdiction des femmes dans les cafés, l'observance d'interdits alimentaires religieux ou l'imposition de certaines relations hommes / femmes doit faire l'objet d'une adaptation au cas par cas.

La logique d'intelligence répartie répond à la décentralisation complète de nos règles, autorisant toutes les compromissions locales à partir du moment où elles sont rentables.

Les motivations de telles démissions sont connues: il s'agit d'une optimisation électorale, une suradaptation à la réalité locale de chaque quartier pour engranger le maximum de voix. Quelle tentation que celle d'un algorithme qui calculerait en permanence les adaptations de la loi en fonction des rapports de force locaux, assurant une paix fondée sur la flexibilité aux revendications des plus majoritaires localement et permettant une maximisation des chances électorales. La logique d'intelligence répartie répond à la décentralisation complète de nos règles, autorisant toutes les compromissions locales à partir du moment où elles sont rentables, économiquement comme électoralement.

Il ne faut pas penser que le monde matériel serait épargné, parce que c'est par le seul biais de morceaux de logiciels que l'IA agit. L'internet des objets remplace la puissance de calcul centralisée dans un PC par des dizaines de petits objets communicants, plus spécialisés et moins puissants qu'un ordinateur, mais agissant de façon redoutablement coordonnée pour gérer notre maison. Étendus au-delà de notre domicile, nous serons environnés de milliers de tels petits objets, interagissant en permanence pour recréer des logiques de réseaux disséminés. Mais qui dit dissémination dit faille: une cyberattaque récente s'est attaquée à des milliers de caméras de surveillance, beaucoup plus difficiles à toutes contrôler et protéger, pour investir des sites internet mondialement fréquentés.

L'étape ultime intervient lorsque la frontière entre le numérique et le vivant se met à céder. Elon Musk affirme que nous sommes déjà des cyborgs, les smartphones et autres objets connectés étant devenus des prothèses prolongeant l'usage de nos membres et de nos sens. Des connexions directes de l'influx nerveux vers nos smartphones sont envisagées, faisant des objets connectés des membres de notre corps à part entière. Enfin, des «nano-bots», robots microscopiques, pourraient être injectés dans notre flux sanguin. Individuellement capables d'opérations très limitées, leur organisation en réseau permettrait d'accomplir des tâches médicales de haute volée. Mais pour cette application de l'intelligence disséminée comme pour d'autres, que se passe-t-il si elle développe sa propre logique par auto-organisation, échappant à la nôtre?

Le jour où la terre s'arrêta et la mémoire d'Athènes

Le danger réel de l'IA et sa résonance troublante avec la dérégulation moderne apparaissent de manière frappante dans les deux versions du film de SF «Le jour où la terre s'arrêta», dans son ancienne version de 1951 et dans celle moderne de 2008. L'extraterrestre chargé de mettre en garde les terriens contre leur prochaine destruction est accompagné d'un robot garde du corps, Gort. Dans la version de 1951, Gort est représenté sous une forme humanoïde compacte et unie, capable de terrasser un adversaire par sa force mécanique ou un rayon émis par une fente oculaire. Il représente le fantasme du cyborg tueur, longtemps populaire, mais dont nous venons de comprendre qu'il n'est pas le vrai danger. Le Gort de la version de 2008, accompagnant Keanu Reeves, est capable de se dissocier en une multitude innombrable de petits insectes mécaniques, pouvant se reproduire, se déplaçant comme une nuée tueuse. La puissance collective de cet essaim est bien plus redoutable que celle du robot de 1951, car elle accomplit à elle seule la tâche de destruction de la terre.

La nouvelle version du film a bien ressenti notre évolution postmoderne. Les menaces ne sont plus un adversaire identifiable et massif, comme l'étaient les totalitarismes classiques. Elles sont fluides, adaptables, se dispersant à tous vents si l'on cherche à les pilonner, se resserrant comme les anneaux d'un python dans une étreinte implacable dès que l'opportunité se présente. Les réactions des marchés financiers à la moindre velléité d'ouvrir d'autres politiques ont cette fluidité des systèmes disséminés et coordonnés en réseau.

Telle est l'IA moderne, amplificateur inouï des dévoiements du libéralisme, car procédant du même principe de suradaptation aux plus petits équilibres locaux et de poursuite d'objectifs qui n'ont plus d'autre règle qu'eux-mêmes. Les humains déjà variables d'ajustement économiques deviendraient les animaux de compagnie des processus de l'IA, tolérés tant qu'ils n'introduisent pas trop d'impuretés dans l'optimisation d'ensemble, rayés d'un trait de crayon numérique plus implacable encore que celui des actionnaires s'ils s'opposent à la marche de l'optimalité.

La parade à ces nuées ardentes? Il faut s'attacher à l'universalité de la loi, rester dans ce domaine irréductiblement athénien, refuser les compromissions de l'adaptation instinctive et opportuniste qui dissout les hommes et l'éthique.

Le danger n'est pas technologique, il est dans le fait que ces intelligences non humaines nous renvoient à notre propre déshumanisation.", "public/images/2.jpg", "NULL"),
					(3, 1, "Par  Vianney Passot", "L'homme augmenté, fantasme d'un monde qui rêve d'abolir la mort... de quelques privilégiés", "Elon Musk, le patron de Tesla, a lancé fin mars son entreprise Neuralink, dont le but est d'augmenter le cerveau humain en lui ajoutant une intelligence artificielle. Pour Mathieu Terence, l'idéal transhumain prôné par l'homme d'affaires relève d'une idéologie liberticide.", "Mathieu TERENCE.- Elon Musk est, avec Mark Zuckerberg, l'un des principaux argentiers du transhumanisme. Rien d'étonnant à cela. La Silicon Valley a repris le flambeau, en Californie, du millénarisme que prônaient il y a quarante ans les tenants du New Age à San Francisco. Simplement leur idéal est aux antipodes de celui, mystique, spirituel et anti-consumériste de ces oncles spirituels. Il est scientiste, matérialiste, et ultra-libéral.

L' « homme augmenté » est le fantasme d'un monde qui a pour but d'abolir la mort de quelques ressortissants, privilégiés.

Au fond, rien là que de très logique: le self made man absolu, tel que Musk l'incarne de façon relative et triomphante, est bel et bien le transhumain. Cet IGM (individu génétiquement modifié) fait de sa personne sa propre petite entreprise dont l'unique but consiste à être le plus rentable possible dans le monde dans lequel il doit s'intégrer. L' «homme augmenté», que les neurosciences et le génie génétique rendent plausible aujourd'hui , est le fantasme d'un monde qui, au lieu de savoir donner à vivre une vie vraie, complète, libre, choisie, ou même simplement digne, à l'ensemble du genre humain, a pour but d'abolir la mort de quelques ressortissants, privilégiés.

Votre dernier ouvrage s'intitule Le transhumanisme est un intégrisme. Pourquoi ce titre?

Les valeurs ultralibérales sont celles que promeut le transhumanisme. L' «Homme augmenté» est un homme dont toutes les performances doivent être accrues pour mieux fonctionner dans la société mondialisée dont il n'est plus que la matière première vaguement hédoniste, sous anesthésie financière -salariée ou indemnisante. Toute utopie propose un nouveau monde en fonction des valeurs dominantes du précédent: jeunesse, efficacité, rentabilité sont celles qu'incarnerait le transhumain.

Aucune religion n'a osé rêver inculquer ses dogmes jusque dans la chair, le corps, les gênes de ses adeptes: le scientisme 2.0 du transhumanisme à la Elon Musk (en France à la Laurent Alexandre ou à la Luc Ferry), scientisme qui ne s'embarrasse pas de scrupules avec l'eugénisme, va jusque-là en programmant, selon sa propre idéologie, les individus à naître, en modifiant les wonder boys ou girls qui croient que la réponse au néant qui les taraude est de l'ordre de la quantité et non de la qualité. Voilà pourquoi je qualifie la doctrine transhumaniste d'intégriste dans un texte bref qui en fait la généalogie et qui en sonde les prophéties.

Avec le développement exponentiel de ce genre de technique, à l'heure d'Internet et du Big Data, a-t-on atteint un point de basculement anthropologique?

Le diagnostique sur l' «arraisonnement» de la nature par la technique, pour ne pas remonter à Prométhée ou Héphaïstos , ne date pas d'hier. Heidegger, Berdaïeff, Bernanos, Anders, Hamsun, plus récemment Sloterdijk, ont pensé cette détermination. A ma modeste mesure, dans mes essais et mes fictions , j'aborde ou médite (pardon pour le grand mot) un changement, en effet d'ordre anthropologique, que j'appelle Technosmose: le moment où la technologie entre en synergie, en symbiose, avec la vie, et où la technique peut être perçue comme une sécrétion du vivant qui assure sa pérennité selon le nouveau contexte écologique à quoi correspond l'anthropocène.

De créature à la vie naturelle, l'homme passe au statut de créateur de vie artificielle.

Au début du vingtième siècle, de façon remarquablement coïncidente, l'homme a acquis la maîtrise de l'atome et du gêne. De créature à la vie naturelle, il passe au statut de créateur de vie artificielle. Cet hybris pose question. La réalité de ce changement est incontestable . Il s'agit plutôt de questionner quel visage univoque on veut lui donner et qui est ce «on» qui prétend savoir très précisément quel est le futur qui doit nous échoir «inéluctablement».

La machine transhumaniste s'est-elle emballée? Peut-on encore fixer des limites, ou est-ce trop tard?

Il ne faut pas imaginer pouvoir endiguer un processus technique qui a acquis, de mutation en mutation, la tournure d'une évolution d'ordre zoologique. On peut par contre démasquer l' idéologie qui tient aujourd'hui à lui donner une forme bien précise, sous le sceau d'une perfection qui n'a jamais été le synonyme, et qui est plutôt le contraire, du beau, du bien et du vrai.

Le fantasme de la fusion entre l'homme et la machine est-il réalisable? Quels dangers pour l'humanité?

Il n'y a jamais qu'un risque à redouter d'une idéologie en générale et du scientisme ultra-libérale en particulier, mais ce risque est fatal: la perte de la liberté . En l'occurence: en éradiquant tout hasard dans le processus du vivant on est sûre de perdre toute possibilité de liberté dans le destin d'un sujet. On peut laisser aux fétichistes du «progrès» le rêve de ce monde parfait. De mon côté, sans y croire, j'attends le «transhumaniste» qui défendra le projet d'un nouvel humain plus paresseux, moins docile, plus intraitable, plus laid, plus imperméable à toute idée de ", "public/images/3.jpg", "NULL"),
					(4, 1, "Par  Nicolas Le Dévédec", "Fin des Lumières : bienvenue dans le meilleur des mondes transhumanistes", "Google ou PayPal investissent des milliards de dollars dans le «transhumanisme». Pour Nicolas Le Dévédec, ce projet, dont on perçoit les premiers effets sociaux et économiques, bouleverse la conception de l'homme héritée des Lumières.", "Docteur en Sociologie et en Science politique, Nicolas Le Dévédec est professeur adjoint en Sociologie à HEC Montréal. Il est l'auteur de l'ouvrage La société de l'amélioration. La perfectibilité humaine des Lumières au transhumanisme (éd. Liber, 2015).

«Changer l'être humain plutôt que changer le monde», telle pourrait être résumée la rupture introduite par le transhumanisme quant à la conception de la perfectibilité humaine. Il ne s'agit désormais plus tant d'améliorer la société et nos conditions de vie sociales par des moyens politiques, mais d'améliorer l'humain par des moyens technoscientifiques dans une optique adaptative. Ce renversement marque une rupture importante avec la culture humaniste des Lumières, qui encourageait au contraire les êtres humains à conquérir leur autonomie sociale et politique.

Il ne s'agit plus d'améliorer la société et nos conditions de vie sociales par des moyens politiques, mais d'améliorer l'humain par des moyens technoscientifiques;

Il ne se passe pas un jour ou presque sans qu'on parle du mouvement transhumaniste et de son ambition d'«améliorer» techniquement l'être humain et ses performances intellectuelles, physiques et émotionnelles. Militant en faveur d'un humain revu et corrigé par les technosciences et bénéficiant du soutien de géants économiques comme Google ou PayPal, le transhumanisme ne cesse en effet de gagner en notoriété. Les idéaux d'un «humain augmenté» trouvent un écho certain dans nos sociétés obnubilées par le culte de la performance . Chirurgie esthétique, dopage sportif, recours aux psychostimulants pour optimiser les capacités cognitives ou développement d'une médecine régénératrice qui œuvre à repousser la mort en sont quelques-unes des manifestations saillantes.

Suscitant depuis plusieurs années d'importants débats, force est de constater que le transhumanisme demeure toutefois essentiellement interrogé dans une perspective bioéthique gestionnaire et utilitariste centrée sur la minimisation des risques et la maximisation des avantages de l'humain augmenté. Dans cette perspective, recourir aux technologies d'augmentation serait souhaitable à condition d'en assurer la régulation. À l'image de l'association française transhumaniste Technoprog, qui se revendique d'un transhumanisme social et entend promouvoir un humain augmenté responsable, les considérations éthiques portent dans cette optique régulatrice sur le respect d'un certain nombre de principes, parmi lesquels le respect des droits et des libertés individuelles, l'égalité d'accès aux technologies d'amélioration ou encore leur sécurité en terme de santé.

Cette approche bioéthique libérale s'apparente davantage à un «outil de management du risque» qu'à un véritable outil de réflexion.

S'apparentant davantage à un «outil de management du risque» qu'à un véritable outil de réflexion fondamentale, cette approche bioéthique libérale aujourd'hui dominante néglige considérablement les questions de fond posées par l'humain augmenté et l'idéologie transhumaniste. Quand bien même l'augmentation humaine serait parfaitement libre et éclairée, l'égalité d'accès à ces technologies entièrement garantie et leur utilisation sans dangers pour la santé et la sécurité des individus, serait-elle en effet encore souhaitable? C'est notre conception philosophique de la perfectibilité humaine qu'il est nécessaire d'interroger ainsi que le modèle de société politique que recouvre le transhumanisme. En quoi l'être humain est-il au juste perfectible et pour quel projet de société?

Interrogé dans cette perspective, il apparaît qu'en dépit de la variété de ses expressions, qu'il soit californien, français, libertarien ou prétendument social, le transhumanisme est porteur d'une conception de la perfectibilité humaine résolument adaptative et dépolitisée, en rupture avec l'humanisme des Lumières. La perspective privilégiée par le transhumanisme, même quant à la branche qui se veut plus «sociale» et «progressiste» du mouvement, est en définitive toujours celle de changer techniquement l'être humain en lui-même plutôt que celle de questionner politiquement notre environnement social, dans une perspective critique et réflexive. Dans le meilleur des mondes transhumanistes, jamais ne questionne-t-on réellement et sérieusement l'ordre social aujourd'hui dominant et ses valeurs centrales que sont la performance, le dépassement de soi, la croissance, la productivité et la flexibilité illimitées. Les transhumanistes proposent plutôt de nous y accommoder chimiquement et biologiquement. L'adaptation est le mot d'ordre.

Dans le meilleur des mondes transhumanistes, jamais ne questionne-t-on l'ordre social .

Prenons un seul exemple pour illustrer ce point. Dans un article au titre évocateur, L'ingénierie humaine et le changement climatique, plusieurs scientifiques affiliés au transhumanisme envisagent le plus sérieusement du monde de recourir à des formes de modifications technoscientifiques de l'espèce humaine afin de réduire son empreinte écologique et ainsi donner naissance à des êtres éco-techno-responsables . Les modifications envisagées concernent aussi bien l'usage de la pharmacologie pour rendre les êtres humains intolérants à la viande que la production d'êtres humains de petite taille. La logique est aussi imparable que désopilante: réduire la taille des êtres humains, c'est réduire leur consommation. On n'arrête décidément pas le progrès, surtout lorsque l'on s'évertue comme c'est le cas ici à dédouaner la civilisation de la croissance de toute responsabilité dans la crise climatique actuelle.

Le transhumanisme marque une rupture significative à l'égard de la conception humaniste de la perfectibilité humaine.

Cet exemple caricatural a le mérite de mettre en lumière la logique dépolitisante qui caractérise l'idéologie transhumaniste, très bien résumée par le philosophe Michael Sandel: «Changer notre nature pour nous adapter au monde, plutôt que l'inverse, constitue la forme de dépolitisation la plus aboutie. Cela nous dissuade d'exercer notre esprit critique sur le monde, et entrave l'élan en faveur d'une amélioration sociale et politique». En cela, le transhumanisme marque une rupture significative à l'égard de la conception humaniste de la perfectibilité humaine. Du philosophe Nicolas de Condorcet au médecin Pierre-Jean-Georges Cabanis, la volonté de perfectionner techniquement la nature - nature humaine comprise - fait certes déjà partie intégrante du projet moderne. Toutefois, jamais la quête humaniste ne s'est-elle réduite à cette seule dimension.

Dans la lignée du philosophe Jean-Jacques Rousseau, à qui l'on doit en 1755 l'invention du néologisme «perfectibilité» dans son célèbre Discours sur l'origine et les fondements de l'inégalité parmi les hommes, l'idée de perfectibilité telle qu'envisagée par les Lumières vise plus fondamentalement la conquête de l'autonomie sociale et politique. En définissant l'être humain comme un être perfectible, Rousseau valorise la capacité humaine à agir réflexivement et politiquement sur le monde. En montrant à travers cette notion que la société est une construction instituée par les hommes, qu'aucune loi n'est autrement dit donnée une fois pour toutes, que la rhétorique de l'adaptation au monde tel qu'il est constitue le ressort de la domination et de l'exploitation, Rousseau établit l'idée que les êtres humains ont la possibilité d'édifier par eux-mêmes une société plus juste et plus décente. Tel est le fondement de l'idéal démocratique.

S'il est trop tôt pour saisir toute la portée de ce renversement historique de la perfectibilité humaine, on peut d'ores et déjà en entrevoir les premières retombées sociales.

En nous intimant à nous modifier biotechnologiquement plutôt qu'à remettre en cause la société de l'amélioration contemporaine, le transhumanisme promeut non pas un rapport autonome à soi et au monde, mais un rapport hétéronome par la subordination individuelle et collective aux normes établies du marché économique et de la quête de performance sans limite. S'il est encore trop tôt pour saisir toute la portée de ce renversement historique de la perfectibilité humaine, on peut toutefois d'ores et déjà en entrevoir les premières retombées sociales. Derrière le fantasme d'un enfant parfait, il y a l'instauration d'un nouvel eugénisme lequel, pour libéral et consenti qu'il soit, encourage comme hier l'instrumentalisation de la vie humaine et l'intolérance croissante à l'égard du handicap. Derrière l'humain maître de ses émotions grâce à la pharmacologie, il y a l'émergence d'un humain complexé et souffrant, de plus en plus médicalisé, développant de nouvelles formes de dépendances et d'addictions. Derrière la quête d'une vie sans fin, il y a le jeunisme et la stigmatisation croissante de la vieillesse appréhendée comme une maladie dont il faudrait absolument guérir. Derrière la volonté d'améliorer biomédicalement l'humain et la vie en elle-même, il y a finalement l'exploitation bioéconomique des corps qui se matérialise chaque jour un peu plus.

L'enfer capitaliste est pavé de bonnes intentions technoscientifiques. La seule avancée à mettre au compte de la société de l'amélioration semble ainsi être celle du marché et du capitalisme, qui trouve dans le surhomme replié sur lui-même la matière première de sa reproduction et de sa régénération. Derrière la vitrine promotionnelle d'un humain plus beau, plus fort, plus intelligent et capable de vivre indéfiniment se profile la marchandisation des corps et de la vie, ainsi que la sociologue Céline Lafontaine le montre très bien dans un ouvrage fort éclairant Le corps marché. En exigeant de chaque individu qu'il soit toujours plus performant et devienne l'entrepreneur toujours plus solitaire et résigné de lui-même, le transhumanisme repousse en définitive continuellement la possibilité d'une vie authentiquement humaine, laquelle suppose d'être partagée plutôt qu'augmentée. Avant de vouloir devenir plus qu'humains, commençons par essayer de devenir plus humains.", "public/images/4.jpg", "NULL"),

					(5, 1, "Par  Patrice de Méritens", "François-Xavier Bellamy/Luc Ferry : mais que restera-t-il des hommes?", "«Un monde de liberté», affirme Luc Ferry; «le paradis sur terre est la voie de l'enfer immédiat», lui répond François-Xavier Bellamy, le prochain invité des rencontres du Figaro salle Gaveau.", "Comment définissez-vous le transhumanisme? D'où vient-il?

Luc FERRY. - Le transhumanisme est un rejeton de la troisième révolution industrielle, celle du numérique et des fameuses NBIC: nanotechnologies, biotechnologies, informatique et cognitivisme (l'intelligence artificielle). Il se caractérise par trois traits fondamentaux qui risquent de bouleverser nos vies. D'abord, le projet de passer d'une médecine thérapeutique à une médecine de «l'augmentation», notamment par le biais de l'ingénierie génétique et de l'hybridation. Un exemple? La vision peut être aujourd'hui rendue à des aveugles par implantation d'une puce électronique derrière la rétine. Là, on reste encore dans le cadre thérapeutique. Mais, le jour où cet implant permettrait de nous donner une vue d'aigle, alors la concurrence entre les armées, par exemple, voire entre les familles, pourrait faire passer du thérapeutique à l'augmentatif. Le deuxième trait du transhumanisme, c'est un nouvel eugénisme dont la formule est «From chance to choice»: il s'agit de passer des aléas très inégalitaires de la loterie génétique au choix délibéré d'une amélioration de l'humain grâce à l'ingénierie génétique. On en est loin encore, mais la science progresse tellement vite qu'il n'est pas impossible qu'on y arrive un jour. Le dernier trait -symbolisé par la filiale de biotechnologies de Google, Calico- vise carrément l'augmentation de la vie humaine. Pour une vingtaine d'années dans un premier temps, avec, pour projet à long terme, de lutter contre le vieillissement et la mort. L'université de Rochester vient de réussir à augmenter de 30% la vie de souris transgéniques. Attention, pas de délire: les humains ne sont pas des souris, mais le projet de faire pour eux la même chose est là, financé de manière colossale par Google, ce qui doit nous inciter à y réfléchir dès maintenant.

«Cette révolution transforme l'idée que nous nous faisons de l'homme»

François-Xavier Bellamy

François-Xavier BELLAMY - Cette révolution ne compte pas seulement bouleverser nos vies, elle transforme l'idée que nous nous faisons de l'homme. Pallier une rétinite par le biais d'un implant, c'est rendre à l'homme ses deux yeux, le reconduire à l'équilibre naturel des corps humains. Se faire greffer un troisième œil derrière la tête serait totalement différent; en fait, le transhumanisme se fonde sur une anthropologie de la frustration: vouloir «augmenter» l'humain, c'est le considérer comme un être déficient. Depuis toujours, la médecine thérapeutique voulait réparer la nature; le transhumanisme veut la détruire. Dès lors que la technique quitte la médecine pour basculer dans l'augmentation, c'est son mépris de la faiblesse et de la fragilité qu'elle trahit, et c'est à nous-mêmes que nous déclarons la guerre…

Luc FERRY - La technomédecine et l'ubérisation de la planète vont bouleverser nos vies et le monde de la technique nous submerge: ses avancées sont si rapides et si difficiles à comprendre qu'elles échappent aux politiques comme aux opinions publiques. Avec ses milliers de laboratoires et de leviers de décision, la technoscience échappe presque à tout contrôle, et ce que nous régulerons en France ne fixera rien en Corée ou en Chine. D'où l'avertissement des «bio-conservateurs» tels que Francis Fukuyama ou Michael Sandel, qui appellent à anticiper. Qui aurait pu dire il y a seulement cinquante ans qu'un ordinateur battrait le champion du monde de go? Et qui peut dire ce que seront les biotechs en 2300? Leur augmentation exponentielle nous approche des limites technologiques de la démocratie, et c'est un problème politique: on ne pourra ni tout interdire ni tout autoriser, il faudra repenser de fond en comble la notion de régulation et pas seulement au niveau national. Il existe, pour se repérer en éthique, deux grandes traditions humanistes. L'humanisme chrétien qui, avec saint Thomas, privilégie l'idée de loi naturelle. L'humanisme laïc, celui de Pic de La Mirandole et de Condorcet: il définit l'humain non par ses qualités naturelles mais, au contraire, par sa liberté, par sa faculté de transgresser la nature de sorte qu'il est capable d'une perfectibilité infinie, y compris sur le plan biologique. C'est à la fois fascinant et effrayant. Car si la mort et la vieillesse sont naturelles, lutter contre elles ne l'est pas moins: quand le médecin vous annonce un cancer du pancréas, d'un coup, vous regardez d'un œil moins critique les possibilités que le transhumanisme prétend offrir un jour à une humanité augmentée… François-Xavier BELLAMY - Non! Vous espérez la guérison, et vous avez raison. Rien à voir avec le transhumanisme… On peut vouloir un corps humain en bonne santé, sans courir derrière un corps surhumain - et du même coup inhumain… Vous évoquez «l'humanisme» des transhumanistes mais, dans la volonté de refuser que l'homme partage une nature commune, je vois plutôt une forme d'antihumanisme. C'est au fond la haine de l'homme dans les finitudes qui définissent sa condition - dans sa fragilité, dans la vieillesse, la maladie et la mort. Et pourtant, les dernières découvertes de la chronobiologie montrent combien ces limites font partie de nos vies - jusque dans nos cellules, dont Jean-Claude Ameisen décrit le renouvellement permanent comme une inscription de l'éphémère au cœur de la vie. Voilà notre condition. Nous sommes des vivants aussi par la mort. Il est bon que la médecine lutte pour la vie; mais elle reniera la vie humaine quand elle tentera de supprimer la mort. Quand nos corps mortels seront remplacés, organe par organe, par des pièces de machine, serons-nous encore humains? Serons-nous vraiment vivants? C'est là tout l'enjeu anthropologique, dont il faut que la politique se saisisse dès maintenant.

Le danger, en effet, serait que nous ouvrions les yeux quand les grandes mutations seront déjà faites. Tout l'enjeu est aujourd'hui de reprendre le pouvoir sur notre propre pouvoir. C'est en redécouvrant le sens de l'humain que nous pourrons retrouver la maîtrise de notre destin commun.

«La guerre contre la nature a une part de légitimité»

Luc Ferry

Luc FERRY - Je crois que la guerre contre la nature a une part de légitimité. Rien n'est moins naturel que la civilité, que la démocratie, que la science…

François-Xavier BELLAMY - Je pense, avec Platon, que la guerre contre la nature est désastreuse. C'est, dans le Gorgias, la question de Calliclès contre Socrate: ne faut-il pas dépasser toutes les limites pour satisfaire ses désirs? Pour Socrate, cette guerre contre la mesure que nous impose la nature nous condamne en fait au malheur, car elle ouvre une surenchère permanente: nous n'en aurons jamais assez. Nous voilà donc prisonniers de nos fantasmes, contraints à une course infinie, et donc vaine - quand bien même on l'appellerait «progrès». Il faut choisir de recevoir et de contempler - ou bien dissoudre sa propre vie dans une fiction. La révolte contre la nature est une malédiction que nous nous infligeons à nous-mêmes.

Luc FERRY - Vous êtes un humaniste chrétien et je me place dans le second humanisme, celui qui pense qu'à la différence des animaux, l'être humain n'est pas emprisonné dans un programme naturel, comme l'abeille qui est préformée pour fabriquer du miel, ou mon chat pour chasser les souris, sans pouvoir jamais s'émanciper de ce logiciel de la nature. Je suis plus du côté de Protagoras que de Platon dans l'idée que le meilleur de l'humain consiste justement à s'affranchir de la nature. Tout est-il permis pour autant? Evidemment, non! Le fameux «Il est interdit d'interdire» de 1968 est la plus grande ânerie de l'histoire humaine! Le défi de l'humanisme laïc est justement de fabriquer des limites spécifiquement humaines, non naturelles. Et c'est là le sens du fameux précepte républicain selon lequel «ma liberté doit s'arrêter là où commence celle des autres». Il paraît anodin, mais il est en vérité d'une profondeur abyssale: il signifie que les limites sont construites par l'être humain, son intelligence et sa liberté, et non imposées par la nature ou par Dieu. Toute la démocratie et toute la médecine se construisent contre la nature. Le virus du sida tout comme la pandémie de grippe qui a tué 20 millions de personnes en 1918 sont naturels. La nature n'est jamais un modèle moral. Comme disait Spinoza, dans la nature les gros mangent les petits…

François-Xavier BELLAMY - Pour le coup, je serai en profond désaccord avec vous. La médecine thérapeutique, pour ne parler que d'elle, ne se construit jamais contre la nature.

Luc FERRY - Et les antibiotiques?

François-Xavier BELLAMY - Les antibiotiques ne font qu'utiliser, finalement, les réactions naturelles du vivant.

Luc FERRY - Non, le mot même indique qu'on tue des microbes absolument naturels.

François-Xavier BELLAMY - Mais on le fait pour rétablir cet équilibre naturel du corps qui se nomme la santé! Si la médecine intervient, c'est pour restaurer la nature dans son cours ordinaire. Les maladies sont des accidents de la nature.

Luc FERRY - Vous plaisantez! Les maladies, comme la vieillesse et la mort, sont, du point de vue de la totalité de la nature, parfaitement naturelles. Elles n'en sont pas moins des fléaux. La nature comprend tout, le pire comme le meilleur, ce pourquoi l'éducation de nos enfants n'a rien de naturel. Spontanément, nos enfants moquent les différences, les handicaps, ils sont égoïstes et impolis et, croyez-moi, l'apprentissage de la civilité est tout sauf naturel parce que la nature est le contraire absolu d'une norme morale!

François-Xavier BELLAMY - Au contraire… L'éducation pourrait se définir par la maxime du classicisme: «Combien d'art pour rentrer dans la nature!» L'éducation, c'est le travail de la culture qui permet à l'enfant d'accomplir sa propre nature. Il y a quelque chose de profondément naturel chez l'homme dans la civilité, par exemple: par l'exercice bien sûr, par l'artifice, elle nous apprend à être authentiquement humains et fait échapper notre nature profonde à l'immédiateté des pulsions, à la facticité du caprice. Pourquoi, sinon, choisir la morale?

Luc FERRY - Vous défendez la conception grecque et thomiste de la vertu comme actualisation de dispositions naturelles, et c'est bien votre droit. Mais, de mon point de vue d'humaniste laïc, c'est tout l'inverse: la nature est aveugle, injuste, elle ne connaît que la force brute et la vertu morale consiste, non à l'actualiser, à la suivre, mais au contraire à lutter contre elle. Ce qu'il y a de grand dans l'être humain, c'est sa liberté, son travail et ses efforts, pas sa nature, hélas! Il n'y a donc aucune raison de ne pas vouloir la corriger ou l'améliorer parfois. Si on pouvait accroître de vingt ans la vie de ma mère, je serais preneur. La vraie question pour moi est bien plus complexe et c'est celle-ci: à quel prix? Si l'ingénierie génétique fonctionne un jour, elle pourra remettre en cause la définition même de l'humain comme être libre, et c'est un grand danger. Plutôt que des ministères aux intitulés débiles, «l'habitat durable» ou «l'égalité réelle», il faut dès maintenant que les politiques se réveillent sur ces questions. On ne saurait modifier une partie de l'espèce humaine sans que le reste en soit affecté. Tout mon livre plaide pour une régulation qui doit être politique.

François-Xavier BELLAMY - Le technicisme qui voudrait faire croire que tous les problèmes seront réglés par le progrès technique est en effet absurde. La technique ne fait que déplacer les difficultés. Elle ne peut apporter des réponses qu'à des questions qui se formulent en amont de la technique. Le transhumanisme n'est une solution que si nos corps sont perçus comme un problème… Il faut donc résister à ce que Carl Schmitt appelait la neutralisation du monde, l'idée qu'au fond la technique pourrait dissoudre la politique dans des solutions préconstruites. Nos débats politiques cèdent déjà trop souvent à cette facilité en demandant aux «experts» de résoudre pour nous les problèmes. Les vraies questions ne sont pas techniques. Il ne s'agit pas seulement par exemple de trouver comment augmenter la vie, mais de savoir si nous le voulons vraiment: cela nous concerne tous.

Luc FERRY - La technophilie est souvent absurde, en effet, naïve et dangereuse, mais tout dépendra de l'usage qu'on en fera. Allons-nous enrichir l'humain ou l'appauvrir? C'est toute la question.

«Avec la mort de la mort, serons-nous encore des humains ?»

François-Xavier BELLAMY - Quand nous porterons des cœurs qu'on changera tous les cinquante ans, nous n'aurons pas prolongé la vie, nous aurons supprimé la mort. Serons-nous encore des humains? La condition pour la survie de l'humanité sera de ne plus avoir d'enfants, pour une simple raison de place et de richesses à exploiter. Une vie sans générations, est-ce encore une vie humaine? Et cette vie sera-t-elle vraiment la nôtre? C'est la question que posait Jorge Luis Borges dans L'Immortel: si vous avez devant vous un temps infini, il n'y a plus rien que vous seul puissiez faire. La limite qui marque le temps de la vie est aussi la condition de la créativité. Arendt décrivait la natalité comme la condition de toute nouveauté dans le monde. Il y a enfin une dernière raison de craindre que le transhumain ne soit, en fait, l'inhumain: le jour où nous arriverons à supprimer la mort, se posera la question de notre type de société. Ne vivrons-nous pas une régression vers la barbarie, quand ceux qui en ont les moyens s'augmenteront, pendant que les démunis n'auront qu'à disparaître? Nous finissons par céder à une caricature de ce que vous appeliez «la nature», avec notre eugénisme techniciste qui veut supprimer les imparfaits par haine de l'imperfection.

«La victoire sur la mort est un pur fantasme»

Luc Ferry. Luc FERRY - Il n'y a rien de pire que la technophilie, sinon la technophobie! La loi de Moore s'applique aussi à la nouvelle économie. Le premier séquençage du génome humain a coûté 3 milliards de dollars en 2000, il en coûte environ 1 000 aujourd'hui. Quant à la victoire sur la mort, c'est un pur fantasme. Nous finirons toujours par mourir, fût-ce par accident ou par suicide. Nous resterons mortels. Le propre de l'homme s'enracine-t-il pour autant dans une nature figée et intangible, de sorte qu'en bousculant cette nature on modifie aussi ce qui en dépend, à savoir la morale? C'est votre hypothèse et celle de Fukuyama. Mais si on pense au contraire que l'être humain est perfectible à l'infini, que sa liberté transcende la nature, alors l'idée d'augmenter la longévité devient plutôt joyeuse! Il y a tant de livres à lire, tant d'hommes et de femmes à aimer qu'une espérance de vie de 300 ans m'enchanterait! J'entends dire: «Quelle horreur, on va s'ennuyer, est-ce qu'on aimera encore?» Mais pas du tout! On aimera, on apprendra, on s'améliorera. Et, si vous n'en voulez pas, n'en dégoûtez pas les autres…

François-Xavier BELLAMY - Toucher à l'espèce humaine concerne tout le monde. On ne saurait donc dire à ceux qui sont méfiants face à ce nouvel univers qu'ils n'ont qu'à se mettre à l'écart. Si le projet est de construire un monde d'ennui dont la seule perspective de sortie soit le suicide ou l'accident, je ne vois pas où est le progrès qu'on nous vend!

Luc FERRY - C'est en tout cas un monde de liberté. Je ne suis ni transhumaniste ni partisan du suicide, mais l'utopie d'une perfectibilité infinie des humains qui pourrait, pourquoi pas, transformer le monde en paradis ici et maintenant, ne me déplaît pas. Nous en sommes si loin, si loin d'être au niveau de notre liberté!

François-Xavier BELLAMY - La promesse du paradis, ici et maintenant, est la voie la plus sûre vers l'enfer immédiat… La religion comme la philosophie savent que l'homme n'est jamais pleinement au niveau de sa liberté!

Luc FERRY - Mon Dieu, pourquoi les chrétiens devraient-ils se scandaliser à l'idée de faire descendre un peu de leur idéal, celui de la «mort de la mort», du ciel vers la terre?

François-Xavier BELLAMY - La mort de la mort par la vie authentique de la conscience, non par l'inerte matérialité d'artifices techniques déjà morts…", "public/images/5.jpg", "NULL"),

					(6, 1, "Par Luc Vinogradoff", "Le Web que nous avons n’est pas celui dont nous rêvons","La croissance et la diversification des géants d’Internet compromet l’essence même du Web : une plate-forme ouverte permettant à quiconque de partager des informations.", "Nos créations finissent toujours par nous échapper. Tim Berners-Lee, considéré comme le principal inventeur du Web, connaît certainement cet adage. Pour le 28e anniversaire de la naissance du réseau, en mars, il a signé une tribune, traduite en plusieurs langues, dans laquelle il livre son diagnostic sur les dangers qui guettent ce qu’il avait, à ses débuts, « imaginé comme une plate-forme ouverte qui permettrait à quiconque, partout, de partager des informations, de collaborer par-delà les frontières géographiques et culturelles ».

Dynamiques de pouvoir
L’ouverture, la collaboration, l’échange sont dans l’ADN du Web. Mais cet ADN s’est dilué à mesure que ce territoire virtuel devenait plus vaste, plus peuplé, plus commercial, plus dangereux et plus influent que jamais sur notre vie quotidienne. En somme, depuis qu’il est devenu beaucoup moins virtuel. « La bataille pour garder le Web ouvert est sans relâche », écrit Tim ­Berners-Lee, ajoutant : « C’est à nous tous, désormais, de construire le Web que nous voulons. » Il nous pousse ainsi à nous interroger : quelle version du Web sommes-nous encore en mesure d’espérer ?

Début novembre, un autre article a largement circulé en ligne, étayant le diagnostic de Berners-Lee. Signé par André Staltz, programmeur spécialisé dans les logiciels libres, il porte un titre tranchant : « Le Web a commencé à mourir en 2014. » Pour atteindre ce constat, Staltz a simplement regardé de près l’évolution du trafic depuis 2010. « L’activité en ligne en soi n’a pas diminué. Sa croissance est régulière, que ce soit en nombre d’utilisateurs ou de sites », écrit-il. Mais ce développement constant cache « un changement radical dans les dynamiques de pouvoir souterraines sur le Web ».

Concentration
Comme souvent lorsqu’on se penche sur ces « dynamiques de pouvoir », on retrouve ceux qu’on surnomme les « géants du Web » et que Berners-Lee appelle ses « gardiens » : Google,...", "public/images/6.jpg", "NULL");

